title: Venkat Potamsetti
description: Senior Healthcare & Business Data Analyst — SQL · Python · Power BI · Tableau
theme: jekyll-theme-cayman
# Important for project sites:
baseurl: "VenkatPotamsetti"
